IF
  Level(myself,21)
  !HasItemEquiped("ddr!ev06",myself)
  Global("DDR!awk","LOCALS",0)
THEN
  RESPONSE #100
  ChangeClass(myself,SORCERER)
  AddSuperKit(DDRawk)
  AddXPObject(myself,600000)
  DisplayStringHead(Myself,~你体内的龙之血觉醒了。~)
  SetGlobal("DDR!awk","LOCALS",1)
END

IF
  Level(myself,21)
  HasItemEquiped("ddr!ev06",myself)
  Global("DDR!awk","LOCALS",0)
THEN
  RESPONSE #100
  DisplayStringHead(Myself,~龙之血的觉醒被抑制了。~)
  SetGlobal("DDR!awk","LOCALS",2)
END

IF
  GlobalLT("DDR!ats","LOCALS",0)
THEN
  RESPONSE #100
  SetGlobal("DDR!ats","LOCALS",0)
END

IF
  GlobalGT("DDR!ats","LOCALS",99)
THEN
  RESPONSE #100
  ReallyForceSpellRES("ddr!ev07",myself)
  SetGlobal("DDR!ats","LOCALS",0)
END

IF
  !HasItemEquiped("ddx002b",myself)
THEN
  RESPONSE #100
  ReallyForceSpellRES("ddx002x",myself)
END

IF
  Global("DDR!awk","LOCALS",1)
  PartyHasItem("ddr!ev06")
THEN
  RESPONSE #100
  TakePartyItemALL("ddr!ev06")
  DestroyItem("ddr!ev06")
END